### ISSUE TITLE
Minimatch version

### ISSUE THREAD

**Issue by diegosantamarta** [npm/fstream-ignore#14]
I'm getting this error: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

Could you please update this version?

Thanks.
Diego

**Comment by montogeek** [comment]
Please :)

**Comment by isaacs** [comment]
This is actually an issue in npm's deploy bundle, not with this repo specifically.  3.0.2 works just fine to satisfy fstream-ignore's dependency, but npm has a snapshot in its deployed node_modules bundles that needs to be explicitly updated.  (It does it in this way so that npm@3 can be installed properly using npm@2, which is an edge case virtually no other packages have to deal with.)

Posted over at https://github.com/npm/npm/issues/13387
